### ISSUE TITLE
Use the Illustration for a project?

### ISSUE THREAD

**Issue by TeoDev1611** [GolangUA/gopher-logos#3]
Hello, I am currently doing a project with a micro database in go with various formats. I was wondering if I can use an illustration from your repository as an icon for my project. I don't know what credits or who do I have to ask for authorization from? I hope your help thanks

**Comment by TeoDev1611** [comment]
__

**Comment by tenmozes** [comment]
Hi Teo feel free to use any logs 
You need to specify author of logo (we have two RedPanda and Nats Romanova)
more information in license https://creativecommons.org/licenses/by/3.0/

**Comment by TeoDev1611** [comment]
thanks for help
